server:
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recenzije
    username: root
    password: mrm1_m!rc!c

  jpa:
    hibernate:
      ddl-auto: update